apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "sandbox"
  description: "sandbox"
  tags:
    - sx-cnp-oss
    - template
    - metalstack
  links:
    - url: https://grafana-metalstack.platform-engineer.cloud/
      title: Grafana SRE Metrics
      icon: web
  annotations:
    github.com/project-slug: AntoniusUIBK/demo
    backstage.io/kubernetes-id: sandbox
    kubecost.com/deployment-name: sandbox
    argocd/app-name: sandbox
    backstage.io/kubernetes-namespace: uibklab-sandbox
    backstage.io/kubernetes-label-selector: app=sandbox
    kubevirt-manager: "https://kubevirt-manager-metalstack.platform-engineer.cloud/"
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> 'kubevirt')"
    grafana/overview-dashboard: "https://grafana-metalstack.platform-engineer.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=&var-namespace=test-demo-kubevirt&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "uibklab"
  system: sandbox
  dependsOn:
    - resource:argocd
    - resource:kubevirt
    - resource:kubecost
    - resource:k8s-monitoring
    - resource:kubevirt-manager
    - resource:kubevirt
    - resource:loki
